### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/z3c.caching#9]
And maybe consider giving PyPI rights to `plone` or someone else: the other three who can make releases are not actively using Plone as far as I know. (Though I am pretty sure they will happily make a new release or grant rights in a pinch.)

**Comment by icemac** [comment]
@mauritsvanrees I do not have the owner role so I am not able to add new maintainers to the project. I am a little low on time now. Hopefully I could cut a release tomorrow.

**Comment by icemac** [comment]
Just released 2.2 to PyPI, see https://pypi.org/project/z3c.caching/2.2/

**Comment by mauritsvanrees** [comment]
Thank you! I have updated Plone coredev 5.2.

**Comment by mauritsvanrees** [comment]
@wichert Since you made the first release of `z3c.caching`, are you the Owner on PyPI? Could grant the `plone` user the maintainer role and/or upgrade `icemac` to Owner?

**Comment by icemac** [comment]
@wichert Any news on this issue?

**Comment by wichert** [comment]
@icemac I've made you an owner

**Comment by icemac** [comment]
@wichert Thank you!
@mauritsvanrees I just added `plone` as maintainer.

**Comment by mauritsvanrees** [comment]
Thank you both!
